name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm test

      - name: Deploy to Server (You'll need to provide your server deployment steps here)
        run: |
          # Replace this with your deployment steps
          # e.g., you can use SSH to deploy to your server
          # ssh user@your-server 'cd /path/to/your/app && git pull origin main'

